Repository web3infra-foundation/mega, pull requests merged in 2023-11, with the labels that each got.

#216 Update the README.md and upgrade Cargo.toml
  craft/Cargo.toml
  craft/README.md
  craft/src/main.rs
  git/Cargo.toml
Labels: documentation

#220 Update the README and craft/README
  README.md
  craft/README.md
Labels: documentation

#232 Update README.md
  README.md
  archived/README.md
Labels: documentation

#256 Add empty workspace for cargo build command
  craft/Cargo.toml
Labels: bug

#262 Remove the author from command and update README
  craft/README.md
  craft/src/main.rs
Labels: documentation

#265 Refactoring the core of Mega #238
  mercury/src/internal/mod.rs
  mercury/src/internal/object/mod.rs
  mercury/src/internal/pack/mod.rs
  mercury/src/lib.rs
Labels: refactoring

#270 Refactoring the hash to SHA1, add comments and test case #238
  mercury/src/hash.rs
Labels: documentation, refactoring

#272 Add decode object header function for pack file
  mercury/src/internal/object/mod.rs
  mercury/src/internal/pack/mod.rs
Labels: refactoring

#271 upgrade axum to 0.7 and refactoring some apis
  gateway/Cargo.toml
  gateway/src/api_service/obj_service.rs
  gateway/src/git_http.rs
  gateway/src/https.rs
  gateway/src/lfs.rs
  gateway/src/lib.rs
  git/Cargo.toml
  git/src/lfs/handler.rs
  git/src/lfs/lfs_structs.rs
  git/src/lfs/mod.rs
  git/src/protocol/mod.rs
Labels: refactoring

#274 optimize http router
  gateway/src/api_service/mod.rs
  gateway/src/api_service/router.rs
  gateway/src/git_http.rs
  gateway/src/https.rs
  gateway/src/lfs.rs
  git/src/lfs/handler.rs
  git/src/lfs/lfs_structs.rs
  mercury/src/internal/pack/mod.rs
Labels: refactoring
