Repository web3infra-foundation/mega, pull requests merged in 2024-10, with the labels that each got.

#633 [lunar] fix build error after upgrade tauri to 2.0.0
  .github/workflows/base.yml
  lunar/package.json
  lunar/src-tauri/Cargo.toml
  lunar/src-tauri/capabilities/migrated.json
  lunar/src-tauri/gen/schemas/acl-manifests.json
  lunar/src-tauri/gen/schemas/capabilities.json
  lunar/src-tauri/gen/schemas/desktop-schema.json
  lunar/src-tauri/gen/schemas/linux-schema.json
  lunar/src-tauri/gen/schemas/macOS-schema.json
  lunar/src-tauri/src/main.rs
  lunar/src-tauri/tauri.conf.json
  lunar/src-tauri/tauri.linux.conf.json
  lunar/src-tauri/tauri.macos.conf.json
  lunar/src-tauri/tauri.windows.conf.json
  lunar/src/app/api/fetcher.ts
  lunar/src/app/application-layout.tsx
  lunar/src/app/settings/page.tsx
  lunar/src/components/RepoList.tsx
Labels: Hacktoberfest2024, client

#646 Upgrade README and random for crates-sync script
  README.md
  scripts/crates-sync/crates-sync.py
Labels: documentation, test

#647 update `Libra` LFS object download for `Moly`
  libra/Cargo.toml
  libra/src/command/lfs.rs
  libra/src/command/restore.rs
  libra/src/internal/protocol/lfs_client.rs
  libra/src/lib.rs
  mega/tests/lfs_test.rs
Labels: lfs

#650 Upgrade packages of lunar
  lunar/package.json
  lunar/src-tauri/Cargo.toml
  lunar/src-tauri/gen/schemas/acl-manifests.json
  lunar/src-tauri/gen/schemas/desktop-schema.json
  lunar/src-tauri/gen/schemas/macOS-schema.json
Labels: ui, client

#660 Upgrade nextjs and tauri for Lunar
  lunar/package.json
  lunar/src-tauri/gen/schemas/acl-manifests.json
  lunar/src-tauri/gen/schemas/desktop-schema.json
  lunar/src-tauri/gen/schemas/linux-schema.json
  lunar/src-tauri/src/main.rs
  lunar/src/app/application-layout.tsx
  lunar/src/app/layout.tsx
  lunar/tsconfig.json
Labels: Hacktoberfest2024, client
