Repository web3infra-foundation/mega, pull requests merged in 2024-05, with the labels that each got.

#374 Update .env.example and remove the MySQL support
  .env
  .env.example
  Cargo.toml
  README.md
  archived/kvcache/Cargo.toml
  archived/kvcache/README.md
  archived/kvcache/src/connector/fake/mod.rs
  archived/kvcache/src/connector/mod.rs
  archived/kvcache/src/connector/redis/mod.rs
  archived/kvcache/src/lib.rs
  archived/kvcache/src/utils.rs
  b_link.txt
  ceres/README.md
  common/README.md
  delta/Cargo.toml
  docs/database.md
  docs/deployment.md
  docs/development.md
  ganymede/README.md
  gateway/README.md
  jupiter/README.md
  libra/README.md
  sql/mariadb/mariadb-dump-20230523.sql
  sql/mysql/mysql_20231106__init.sql
  sql/postgres/pg_20240115__init.sql
  venus/README.md
Labels: documentation, refactoring

#383 Update the README.md and add an architect image #34
  .env
  .env.example
  .gitignore
  Cargo.toml
  README.md
  archived/README.md
  ceres/README.md
  common/README.md
  craft/README.md
  delta/README.md
  docs/api.md
  docs/development.md
  docs/images/architect.svg
  docs/images/mega-architect.png
  ganymede/README.md
  gateway/README.md
  gemini/README.md
  jupiter/README.md
  libra/README.md
  mars/README.md
  mercury/README.md
  moon/README.md
  moon/package-lock.json
  scorpio/README.md
  src/main.rs
  venus/README.md
Labels: documentation

#387 Refactoring the main module and website
  Cargo.toml
  README.md
  craft/Cargo.toml
  mars/README.md
  mars/package.json
  mars/src/app/(auth)/login/page.jsx
  mars/src/app/(auth)/register/page.jsx
  mars/src/app/(main)/page.jsx
  mars/src/app/layout.jsx
  mars/src/app/not-found.jsx
  mars/src/components/Faqs.jsx
  mars/src/components/Footer.jsx
  mars/src/components/Header.jsx
  mars/src/components/Hero.jsx
  src/cli.rs
  src/main.rs
  src/utils/mod.rs
Labels: documentation, refactoring, website

#388 Use bin in the Cargo.toml
  Cargo.toml
  mega/src/build.rs
  mega/src/cli.rs
  mega/src/commands/init.rs
  mega/src/commands/mod.rs
  mega/src/commands/service/https.rs
  mega/src/commands/service/mod.rs
  mega/src/commands/service/p2p.rs
  mega/src/commands/service/ssh.rs
  mega/src/commands/service/start.rs
  mega/src/main.rs
Labels: refactoring

#390 Update the Cargo.toml to workspace
  Cargo.toml
  README.md
  ceres/Cargo.toml
  gateway/Cargo.toml
  jupiter/Cargo.toml
  libra/Cargo.toml
  mars/package.json
  mars/src/components/Footer.jsx
  mars/src/components/Header.jsx
  mars/src/components/Hero.jsx
  mars/src/components/Logo.jsx
  mars/src/components/Pricing.jsx
  mars/src/images/logo.svg
  mega/README.md
  mega/src/commands/service/mod.rs
  mega/src/commands/service/p2p.rs
  mega/src/commands/service/start.rs
  mercury/Cargo.toml
  venus/Cargo.toml
Labels: ui, refactoring

#389 use config to parse config toml, replace dotenvy
  .env
  .env.example
  Cargo.toml
  ceres/src/pack/handler.rs
  ceres/src/pack/import_repo.rs
  ceres/src/pack/monorepo.rs
  ceres/src/protocol/mod.rs
  common/Cargo.toml
  common/src/config.rs
  common/src/lib.rs
  common/src/model.rs
  config.toml
  config_example.toml
  docs/deployment.md
  docs/development.md
  gateway/src/api_service/router.rs
  gateway/src/https_server.rs
  gateway/src/init.rs
  gateway/src/ssh_server.rs
  jupiter/src/context.rs
  jupiter/src/raw_storage/mod.rs
  jupiter/src/storage/git_db_storage.rs
  jupiter/src/storage/git_fs_storage.rs
  jupiter/src/storage/init.rs
  jupiter/src/storage/mega_storage.rs
  mega/src/cli.rs
  mega/src/commands/init.rs
  mega/src/commands/mod.rs
  mega/src/commands/service/https.rs
  mega/src/commands/service/mod.rs
  mega/src/commands/service/ssh.rs
  mega/src/commands/service/start.rs
  mega/src/main.rs
  mercury/Cargo.toml
  tests/common/mod.rs
  tests/integration_test.rs
Labels: documentation, refactoring

#391 Update the Cargo.toml files for workspace and fix UI typo error
  Cargo.toml
  libra/Cargo.toml
  mars/src/components/Footer.jsx
  mega/Cargo.toml
Labels: ui, refactoring

#395 Add build information in the mega with shadow_rs
  Cargo.toml
  mega/Cargo.toml
  mega/src/build.rs
  mega/src/cli.rs
  mega/src/commands/init.rs
  mega/src/commands/service/mod.rs
  mega/src/main.rs
Labels: refactoring

#398 Refactor: Using ReceiverStream in pack encode
  Cargo.toml
  ceres/Cargo.toml
  ceres/src/http/handler.rs
  ceres/src/pack/handler.rs
  ceres/src/pack/import_repo.rs
  ceres/src/pack/monorepo.rs
  ceres/src/protocol/smart.rs
  common/src/config.rs
  gateway/src/git_protocol/ssh.rs
  libra/src/command/push.rs
  mega/config.toml
  mega/config.toml.example
  mercury/Cargo.toml
  mercury/src/internal/object/commit.rs
  mercury/src/internal/pack/encode.rs
Labels: enhancement, rust, refactoring

#400 fix bug: incremental_pack repeated count obj num
  ceres/src/pack/handler.rs
  ceres/src/pack/import_repo.rs
  ceres/src/pack/monorepo.rs
  jupiter/src/storage/git_db_storage.rs
  mercury/src/internal/pack/encode.rs
Labels: bug, rust

#405 improve performance, support streaming in decode
  Cargo.toml
  ceres/src/http/handler.rs
  ceres/src/pack/handler.rs
  ceres/src/pack/import_repo.rs
  ceres/src/pack/monorepo.rs
  ceres/src/protocol/mod.rs
  ceres/src/protocol/smart.rs
  common/src/utils.rs
  gateway/src/https_server.rs
  jupiter/Cargo.toml
  jupiter/src/storage/git_db_storage.rs
  jupiter/src/utils/id_generator.rs
  libra/src/command/commit.rs
  libra/src/command/mod.rs
  libra/src/utils/object_ext.rs
  mega/Cargo.toml
  mercury/Cargo.toml
  mercury/src/errors.rs
  mercury/src/internal/model/blob.rs
  mercury/src/internal/model/commit.rs
  mercury/src/internal/model/tree.rs
  mercury/src/internal/object/blob.rs
  mercury/src/internal/object/commit.rs
  mercury/src/internal/object/mod.rs
  mercury/src/internal/object/tag.rs
  mercury/src/internal/object/tree.rs
  mercury/src/internal/pack/entry.rs
Labels: enhancement, rust, refactoring
