Repository web3infra-foundation/mega, pull requests merged in 2024-12, with the labels that each got.

#710 Modify doc and blog of website
  aria/README.md
  aria/contents/blogs/why-rewrite-git-host-service-with-rust-language.mdx
  aria/contents/docs/getting-started/introduction/index.mdx
  aria/next.config.ts
  aria/public/public-og.png
Labels: website

#711 Fix the ssl version number error of nginx conf
  README.md
  aria/contents/docs/components/code-block/index.mdx
  aria/contents/docs/components/custom/index.mdx
  aria/contents/docs/components/image-link/index.mdx
  aria/contents/docs/components/index.mdx
  aria/contents/docs/components/note/index.mdx
  aria/contents/docs/components/project-structure/index.mdx
  aria/contents/docs/components/stepper/index.mdx
  aria/contents/docs/components/tabs/index.mdx
  aria/contents/docs/getting-started/installation/index.mdx
  aria/contents/docs/getting-started/introduction/index.mdx
  aria/lib/routes-config.ts
  docker/README.md
  mercury/src/internal/pack/cache_object.rs
Labels: documentation, Dockerfile

#712 Refactor the docs of website
  aria/README.md
  aria/app/layout.tsx
  aria/contents/docs/getting-started/components/code-block/index.mdx
  aria/contents/docs/getting-started/components/custom/index.mdx
  aria/contents/docs/getting-started/components/image-link/index.mdx
  aria/contents/docs/getting-started/components/index.mdx
  aria/contents/docs/getting-started/components/note/index.mdx
  aria/contents/docs/getting-started/components/stepper/index.mdx
  aria/contents/docs/getting-started/components/tabs/index.mdx
  aria/contents/docs/getting-started/customize/index.mdx
  aria/contents/docs/getting-started/installation/index.mdx
  aria/contents/docs/getting-started/project-structure/index.mdx
  aria/contents/docs/getting-started/themes/index.mdx
  aria/contents/docs/git/index.mdx
  aria/contents/docs/git/pack/index.mdx
  aria/contents/docs/libra/command/add/index.mdx
  aria/contents/docs/libra/command/branch/index.mdx
  aria/contents/docs/libra/command/clone/index.mdx
  aria/contents/docs/libra/command/commit/index.mdx
  aria/contents/docs/libra/command/config/index.mdx
  aria/contents/docs/libra/command/diff/index.mdx
  aria/contents/docs/libra/command/fetch/index.mdx
  aria/contents/docs/libra/command/index-pack/index.mdx
  aria/contents/docs/libra/command/index.mdx
  aria/contents/docs/libra/command/init/index.mdx
  aria/contents/docs/libra/command/lfs/index.mdx
  aria/contents/docs/libra/command/log/index.mdx
  aria/contents/docs/libra/command/merge/index.mdx
  aria/contents/docs/libra/command/pull/index.mdx
  aria/contents/docs/libra/command/push/index.mdx
  aria/contents/docs/libra/command/rebase/index.mdx
  aria/contents/docs/libra/command/remote/index.mdx
  aria/contents/docs/libra/command/reset/index.mdx
  aria/contents/docs/libra/command/restore/index.mdx
  aria/contents/docs/libra/command/rm/index.mdx
  aria/contents/docs/libra/command/status/index.mdx
  aria/contents/docs/libra/command/switch/index.mdx
  aria/contents/docs/libra/command/tag/index.mdx
  aria/contents/docs/libra/config/gitattributes/index.mdx
  aria/contents/docs/libra/config/gitignore/index.mdx
  aria/contents/docs/libra/config/index.mdx
  aria/contents/docs/libra/config/lfs/index.mdx
  aria/contents/docs/libra/index.mdx
  aria/contents/docs/libra/internal/index.mdx
  aria/contents/docs/libra/internal/scheme/index.mdx
  aria/lib/routes-config.ts
  aria/vercel.json
Labels: documentation, website

#714 Refactoring docs of website
  aria/contents/docs/components/aria/index.mdx
  aria/contents/docs/components/aries/index.mdx
  aria/contents/docs/components/atlas/index.mdx
  aria/contents/docs/components/blackhole/index.mdx
  aria/contents/docs/components/ceres/index.mdx
  aria/contents/docs/components/code-block/index.mdx
  aria/contents/docs/components/custom/index.mdx
  aria/contents/docs/components/gateway/index.mdx
  aria/contents/docs/components/gemini/index.mdx
  aria/contents/docs/components/jupiter/index.mdx
  aria/contents/docs/components/mega/index.mdx
  aria/contents/docs/components/mercury/index.mdx
  aria/contents/docs/components/mono/index.mdx
  aria/contents/docs/components/moon/index.mdx
  aria/contents/docs/components/neptune/index.mdx
  aria/contents/docs/components/note/index.mdx
  aria/contents/docs/components/saturn/index.mdx
  aria/contents/docs/components/scorpio/index.mdx
  aria/contents/docs/components/stepper/index.mdx
  aria/contents/docs/components/tabs/index.mdx
  aria/contents/docs/components/taurus/index.mdx
  aria/contents/docs/components/vault/index.mdx
  aria/lib/routes-config.ts
Labels: documentation, website

#722 Upgrade and add more doc sections of website
  aria/contents/docs/architecture/api/index.mdx
  aria/contents/docs/architecture/api/mega/index.mdx
  aria/contents/docs/architecture/api/mono/index.mdx
  aria/contents/docs/architecture/index.mdx
  aria/contents/docs/components/index.mdx
  aria/lib/routes-config.ts
  aria/package.json
Labels: website

#725 fix(tree): Fixed code directory routing issue
  moon/src/components/RepoTree.tsx
Labels: ui

#772 Read Google Analytics id from process env
  moon/.env.local
  moon/src/app/layout.tsx
Labels: ui

#732 Add libra config command
  libra/src/cli.rs
  libra/src/command/config.rs
  libra/src/command/mod.rs
  libra/src/internal/config.rs
Labels: client

#776 Add deployment contents of website
  aria/contents/docs/deployment/compose/index.mdx
  aria/contents/docs/deployment/dockerfile/index.mdx
  aria/contents/docs/deployment/helm/index.mdx
  aria/contents/docs/deployment/index.mdx
  aria/contents/docs/deployment/kubernetes/index.mdx
  aria/lib/routes-config.ts
Labels: ui, website

#783 Fix the docker images of website
  aria/contents/docs/getting-started/installation/index.mdx
Labels: website
