Repository web3infra-foundation/mega, pull requests merged in 2024-09, with the labels that each got.

#548 Refactoring the README and add comments in the PostgreSQL Dockerfile
  README.md
  docker/mono-pg-dockerfile
Labels: documentation, Dockerfile

#561 Update the README.md of Docker
  docker/README.md
Labels: documentation

#563 Fix the .dockerignore and improve README of project
  .dockerignore
  README.md
Labels: documentation

#567 Update Dockerfiles of mono and aries
  docker/aries-engine-dockerfile
  docker/mono-engine-dockerfile
Labels: Dockerfile

#570 Update the DevContainer
  .devcontainer/setup.sh
Labels: Dockerfile

#573 Add crates sync to monorepo script
  scripts/crates-sync/README.md
  scripts/crates-sync/crates-sync.py
Labels: test

#575 Update sync crates files to Monorepo script
  scripts/crates-sync/crates-sync.py
Labels: test, script

#577 Improve comments and docs
  jupiter/Cargo.toml
  jupiter/README.md
  jupiter/callisto/Cargo.toml
  jupiter/callisto/README.md
  jupiter/src/lfs_storage/mod.rs
  mega/Cargo.toml
  mercury/Cargo.toml
  mercury/README.md
  mercury/src/internal/object/mod.rs
  mercury/src/internal/pack/cache.rs
  mercury/src/internal/pack/cache_object.rs
  mercury/src/internal/pack/decode.rs
  mercury/src/internal/pack/entry.rs
  mercury/src/internal/pack/mod.rs
  mercury/src/internal/pack/utils.rs
  mono/src/main.rs
Labels: documentation

#579 Fix the sync crate repository path error
  atlas/README.md
  scripts/crates-sync/crates-sync.py
Labels: test

#581 Improve Cargo.toml format
  Cargo.toml
  aries/Cargo.toml
  aries/README.md
  atlas/Cargo.toml
  ceres/Cargo.toml
  gemini/Cargo.toml
  libra/Cargo.toml
  saturn/Cargo.toml
  scorpio/Cargo.toml
  vault/Cargo.toml
Labels: documentation

#584 Remove crate version valid function from script
  scripts/crates-sync/crates-sync.py
Labels: test

#599 Add Kubernetes deployment
  docker/README.md
Labels: deployment

#601 Improve the stdout with color
  scripts/crates-sync/crates-sync.py
Labels: test

#615 Update Axum version and sync crates script
  Cargo.toml
  scripts/crates-sync/crates-sync.py
Labels: test

#620 add lexical rich component in mr comment
  ceres/src/api_service/mono_api_service.rs
  ceres/src/model/mr.rs
  docker/mono-pg-dockerfile
  jupiter/src/storage/mono_storage.rs
  mono/src/api/mr_router.rs
  moon/package.json
  moon/src/app/(dashboard)/mr/[id]/page.tsx
  moon/src/app/api/mr/[id]/comment/route.ts
  moon/src/app/api/mr/comment/[id]/delete/route.ts
  moon/src/app/host/route.ts
  moon/src/components/MRComment.tsx
  moon/src/components/rich-editor/ExampleTheme.ts
  moon/src/components/rich-editor/LexicalContent.tsx
  moon/src/components/rich-editor/RichEditor.tsx
  moon/src/components/rich-editor/icons/LICENSE.md
  moon/src/components/rich-editor/icons/arrow-clockwise.svg
  moon/src/components/rich-editor/icons/arrow-counterclockwise.svg
  moon/src/components/rich-editor/icons/journal-text.svg
  moon/src/components/rich-editor/icons/justify.svg
  moon/src/components/rich-editor/icons/text-center.svg
  moon/src/components/rich-editor/icons/text-left.svg
  moon/src/components/rich-editor/icons/text-paragraph.svg
  moon/src/components/rich-editor/icons/text-right.svg
  moon/src/components/rich-editor/icons/type-bold.svg
  moon/src/components/rich-editor/icons/type-italic.svg
  moon/src/components/rich-editor/icons/type-strikethrough.svg
  moon/src/components/rich-editor/icons/type-underline.svg
  moon/src/components/rich-editor/plugins/ToolbarPlugin.tsx
  moon/src/components/rich-editor/plugins/TreeViewPlugin.tsx
  moon/src/components/rich-editor/styles.css
Labels: ui

#623 Upgrade PostgresSQL to 17.0 of Dockerfile
  .github/workflows/base.yml
  docker/mono-pg-dockerfile
  scripts/crates-sync/crates-sync.py
Labels: test
