Repository web3infra-foundation/mega, pull requests merged in 2025-04, with the labels that each got.

#935 为 Scorpio 文件系统实现暂存区和 Add 功能
  scorpio/src/daemon/git.rs
  scorpio/src/daemon/mod.rs
  scorpio/src/manager/diff.rs
  scorpio/src/manager/mod.rs
  scorpio/src/manager/store.rs
Labels: r2cn, FUSE

#940 Add more dependecies of monobean in MacOS
  monobean/README.md
Labels: documentation, client

#944 [libra] 提供 .gitignore 支持
  aria/contents/docs/libra/config/gitignore/index.mdx
  libra/Cargo.toml
  libra/src/command/add.rs
  libra/src/command/diff.rs
  libra/src/command/status.rs
  libra/src/utils/lfs.rs
  libra/src/utils/util.rs
Labels: client, pre-task, r2cn

#947 关于 Add 暂存区实现方案的修改和完善
  scorpio/Cargo.toml
  scorpio/src/manager/add.rs
  scorpio/src/manager/diff.rs
  scorpio/src/manager/fetch.rs
  scorpio/src/manager/mod.rs
  scorpio/src/manager/store.rs
  scorpio/src/scolfs/lfs.rs
Labels: r2cn, FUSE

#948 为 Scorpio 模块实现 Git status 命令
  scorpio/src/daemon/git.rs
  scorpio/src/daemon/mod.rs
  scorpio/src/manager/add.rs
  scorpio/src/manager/mod.rs
  scorpio/src/manager/reset.rs
  scorpio/src/manager/status.rs
Labels: rust, r2cn, FUSE

#956 [scorpio]: Optimize directory pulling using a lock-free queue.
  scorpio/Cargo.toml
  scorpio/src/dicfuse/async_io.rs
  scorpio/src/dicfuse/store.rs
Labels: rust, FUSE

#965 P2P: Remove useless or duplicate code
  gateway/src/api/mod.rs
  gateway/src/api/nostr_router.rs
  gateway/src/api/p2p_router.rs
  gateway/src/https_server.rs
  gemini/src/p2p/client.rs
  gemini/src/p2p/mod.rs
Labels: decentralized

#971 CI: run test on self-hosted Arch Linux
  .github/workflows/base.yml
Labels: test, CI

#969 [Scorpio]: Implementing Git Commit Command for Scorpio Module
  scorpio/Cargo.toml
  scorpio/src/daemon/git.rs
  scorpio/src/daemon/mod.rs
  scorpio/src/dicfuse/tree_store.rs
  scorpio/src/manager/add.rs
  scorpio/src/manager/commit.rs
  scorpio/src/manager/diff.rs
  scorpio/src/manager/fetch.rs
  scorpio/src/manager/mod.rs
  scorpio/src/manager/push.rs
  scorpio/src/manager/status.rs
  scorpio/src/manager/store.rs
  scorpio/src/scolfs/lfs.rs
Labels: r2cn, FUSE
