Repository web3infra-foundation/mega, pull requests merged in 2025-05, with the labels that each got.

#997 Add zerofrom and other crates
  Cargo.toml
  libra/src/utils/client_storage.rs
  third-party/BUCK
  third-party/rust/crates/stable_deref_trait/1.2.0/.cargo_vcs_info.json
  third-party/rust/crates/stable_deref_trait/1.2.0/.gitignore
  third-party/rust/crates/stable_deref_trait/1.2.0/BUCK
  third-party/rust/crates/stable_deref_trait/1.2.0/Cargo.toml
  third-party/rust/crates/stable_deref_trait/1.2.0/Cargo.toml.orig
  third-party/rust/crates/stable_deref_trait/1.2.0/LICENSE-APACHE
  third-party/rust/crates/stable_deref_trait/1.2.0/LICENSE-MIT
  third-party/rust/crates/stable_deref_trait/1.2.0/README.md
  third-party/rust/crates/stable_deref_trait/1.2.0/src/lib.rs
  third-party/rust/crates/synstructure/0.13.1/.cargo_vcs_info.json
  third-party/rust/crates/synstructure/0.13.1/BUCK
  third-party/rust/crates/synstructure/0.13.1/Cargo.toml
  third-party/rust/crates/synstructure/0.13.1/Cargo.toml.orig
  third-party/rust/crates/synstructure/0.13.1/LICENSE
  third-party/rust/crates/synstructure/0.13.1/README.md
  third-party/rust/crates/synstructure/0.13.1/src/lib.rs
  third-party/rust/crates/synstructure/0.13.1/src/macros.rs
  third-party/rust/crates/zerofrom-derive/0.1.4/.cargo_vcs_info.json
  third-party/rust/crates/zerofrom-derive/0.1.4/BUCK
  third-party/rust/crates/zerofrom-derive/0.1.4/Cargo.lock
  third-party/rust/crates/zerofrom-derive/0.1.4/Cargo.toml
  third-party/rust/crates/zerofrom-derive/0.1.4/Cargo.toml.orig
  third-party/rust/crates/zerofrom-derive/0.1.4/LICENSE
  third-party/rust/crates/zerofrom-derive/0.1.4/README.md
  third-party/rust/crates/zerofrom-derive/0.1.4/examples/zf_derive.rs
  third-party/rust/crates/zerofrom-derive/0.1.4/src/lib.rs
  third-party/rust/crates/zerofrom-derive/0.1.4/src/visitor.rs
  third-party/rust/crates/zerofrom/0.1.4/.cargo_vcs_info.json
  third-party/rust/crates/zerofrom/0.1.4/BUCK
  third-party/rust/crates/zerofrom/0.1.4/Cargo.toml
  third-party/rust/crates/zerofrom/0.1.4/Cargo.toml.orig
  third-party/rust/crates/zerofrom/0.1.4/LICENSE
  third-party/rust/crates/zerofrom/0.1.4/README.md
  third-party/rust/crates/zerofrom/0.1.4/src/lib.rs
  third-party/rust/crates/zerofrom/0.1.4/src/macro_impls.rs
  third-party/rust/crates/zerofrom/0.1.4/src/zero_from.rs
Labels: buck2, test, CI

#998 ci(release): release libra binary and monobean installer for `windows_x64`,`linux_x86_64` and `macos_aarch64`
  .github/install-dep/action.yml
  .github/workflows/base.yml
  .github/workflows/release.yml
  monobean/Cargo.toml
  monobean/resources/gtk/hello_page.ui
  monobean/resources/icons/scalable/apps/mono-black-logo.ico
  monobean/resources/icons/scalable/apps/mono-white-logo.ico
  monobean/resources/packager_aarch64-apple-darwin.toml
  monobean/resources/packager_x86_64-pc-windows-msvc.toml
  monobean/resources/packager_x86_64-unknown-linux-gnu.toml
  monobean/setup.py
  monobean/src/application.rs
  monobean/src/main.rs
Labels: client

#1000 add comments at libra's command tests.
  .github/workflows/base.yml
  libra/Cargo.toml
  libra/src/command/add.rs
  libra/src/command/branch.rs
  libra/src/command/checkout.rs
  libra/src/command/clone.rs
  libra/src/command/commit.rs
  libra/src/command/diff.rs
  libra/src/command/init.rs
  libra/src/command/log.rs
  libra/src/command/mod.rs
  libra/src/command/push.rs
  libra/src/command/status.rs
  libra/src/command/switch.rs
  libra/src/internal/protocol/lfs_client.rs
  libra/src/utils/client_storage.rs
  libra/src/utils/util.rs
  libra/tests/common/mod.rs
  libra/tests/mega_test.rs
  mega/Cargo.toml
  mega/tests/lfs_test.rs
Labels: test, r2cn, 已认领, CI

#1003 Clean dependencies with workspace in Cargo.toml files
  Cargo.toml
  aria/contents/docs/architecture/api/mono/code-preview/blob/index.mdx
  aria/contents/docs/architecture/api/mono/code-preview/tree/index.mdx
  aria/contents/docs/development/config-file/index.mdx
  aria/contents/docs/development/quick-start/index.mdx
  ceres/Cargo.toml
  ceres/src/pack/import_repo.rs
  common/config.toml
  common/src/config.rs
  config/README.md
  config/config.toml
  docker/README.md
  docker/config.toml
  docs/development.md
  gemini/Cargo.toml
  gemini/src/nostr/client_message.rs
  gemini/src/nostr/event.rs
  gemini/src/p2p/mod.rs
  gemini/src/util.rs
  libra/Cargo.toml
  libra/src/utils/client_storage.rs
  mega/Cargo.toml
  mega/config.toml
  mega/tests/lfs_test.rs
  mercury/Cargo.toml
  mono/Cargo.toml
  mono/config.toml
  mono/src/cli.rs
  mono/src/lib.rs
  monobean/Cargo.toml
  monobean/resources/gtk/preferences.ui
  monobean/resources/org.Web3Infrastructure.Monobean.gschema.xml
  monobean/src/config.rs
  observatory/README.md
  orion-server/Cargo.toml
  orion-server/README.md
  orion/Cargo.toml
  orion/README.md
  saturn/Cargo.toml
  saturn/README.md
  scorpio/Cargo.toml
  scorpio/README.md
  scorpio/src/daemon/git.rs
  scorpio/src/dicfuse/store.rs
  scorpio/src/manager/fetch.rs
  scorpio/src/scolfs/lfs.rs
  scorpio/test/start.sh
  scripts/crates-sync/crates-sync.py
  tests/README.md
  tests/scripts/push.sh
  vault/Cargo.toml
Labels: refactoring

#1004 fix: resolve cloning and merging issues in Libra module
  libra/src/command/branch.rs
  libra/src/command/checkout.rs
  libra/src/command/clone.rs
  libra/src/command/commit.rs
  libra/src/command/config.rs
  libra/src/command/init.rs
  libra/src/command/log.rs
  libra/src/command/merge.rs
  libra/src/command/mod.rs
  libra/src/command/status.rs
  libra/src/command/switch.rs
  libra/src/internal/db.rs
  libra/src/lib.rs
  libra/src/utils/mod.rs
  libra/src/utils/test.rs
  libra/tests/command/add_test.rs
  libra/tests/command/branch_test.rs
  libra/tests/command/checkout_test.rs
  libra/tests/command/clone_test.rs
  libra/tests/command/commit_test.rs
  libra/tests/command/config_test.rs
  libra/tests/command/diff_test.rs
  libra/tests/command/fetch_test.rs
  libra/tests/command/index_pack_test.rs
  libra/tests/command/init_test.rs
  libra/tests/command/lfs_test.rs
  libra/tests/command/log_test.rs
  libra/tests/command/merge_test.rs
  libra/tests/command/mod.rs
  libra/tests/command/mod_test.rs
  libra/tests/command/pull_test.rs
  libra/tests/command/push_test.rs
  libra/tests/command/remote_test.rs
  libra/tests/command/remove_test.rs
  libra/tests/command/restore_test.rs
  libra/tests/command/status_test.rs
  libra/tests/command/switch_test.rs
  libra/tests/command_test.rs
  libra/tests/common/mod.rs
  libra/tests/mega_test.rs
  mega/tests/lfs_test.rs
Labels: test, r2cn, libra

#1014 feat(cli): suport --dry-run and --ignore-errors option for add command
  libra/src/command/add.rs
  libra/tests/command/commit_test.rs
  libra/tests/command/status_test.rs
  libra/tests/command/switch_test.rs
Labels: client, r2cn, 已认领

#1027 Feat(scorpio):add watch mechanism for mono server directory structure changes
  mercury/src/internal/pack/cache_object.rs
  mercury/src/internal/pack/utils.rs
  mercury/zstdelta/src/zstdelta.rs
  scorpio/src/dicfuse/store.rs
  scorpio/src/dicfuse/tree_store.rs
  scorpio/src/manager/fetch.rs
  scorpio/src/manager/store.rs
Labels: FUSE

#1058 feat(UI): Automatically add new users to the "mega" organization
  moon/apps/web/pages/index.tsx
Labels: ui

#1057 fix: update base action file
  .github/workflows/base.yml
  .github/workflows/web-test.yml
Labels: CI

#1059 feat: migrate the code of the Mr module and fix lint and add dependen…
  moon/apps/web/components/MrView/MRComment.tsx
  moon/apps/web/components/MrView/catalyst/heading.tsx
  moon/apps/web/components/MrView/files-changed.tsx
  moon/apps/web/components/MrView/index.tsx
  moon/apps/web/components/MrView/rich-editor/ExampleTheme.ts
  moon/apps/web/components/MrView/rich-editor/LexicalContent.tsx
  moon/apps/web/components/MrView/rich-editor/RichEditor.tsx
  moon/apps/web/components/MrView/rich-editor/icons/LICENSE.md
  moon/apps/web/components/MrView/rich-editor/icons/arrow-clockwise.svg
  moon/apps/web/components/MrView/rich-editor/icons/arrow-counterclockwise.svg
  moon/apps/web/components/MrView/rich-editor/icons/journal-text.svg
  moon/apps/web/components/MrView/rich-editor/icons/justify.svg
  moon/apps/web/components/MrView/rich-editor/icons/text-center.svg
  moon/apps/web/components/MrView/rich-editor/icons/text-left.svg
  moon/apps/web/components/MrView/rich-editor/icons/text-paragraph.svg
  moon/apps/web/components/MrView/rich-editor/icons/text-right.svg
  moon/apps/web/components/MrView/rich-editor/icons/type-bold.svg
  moon/apps/web/components/MrView/rich-editor/icons/type-italic.svg
  moon/apps/web/components/MrView/rich-editor/icons/type-strikethrough.svg
  moon/apps/web/components/MrView/rich-editor/icons/type-underline.svg
  moon/apps/web/components/MrView/rich-editor/plugins/ToolbarPlugin.tsx
  moon/apps/web/components/MrView/rich-editor/plugins/TreeViewPlugin.tsx
  moon/apps/web/components/MrView/rich-editor/styles.css
  moon/apps/web/components/Sidebar/SiderbarMergeRequest.tsx
  moon/apps/web/components/Sidebar/index.tsx
  moon/apps/web/package.json
  moon/apps/web/pages/[org]/mr/[id].tsx
  moon/apps/web/pages/[org]/mr/index.tsx
  moon/pnpm-lock.yaml
  moon/pnpm-workspace.yaml
Labels: ui

#1067 fix(UI): New user can join mega org without apply
  moon/apps/web/pages/index.tsx
Labels: ui

#1075 feat(UI): add blob page
  archived/moon/.env.local
  moon/apps/web/.eslintrc.js
  moon/apps/web/components/CodeView/BlobView/CodeContent.module.css
  moon/apps/web/components/CodeView/BlobView/CodeContent.tsx
  moon/apps/web/components/CodeView/BlobView/Editor.tsx
  moon/apps/web/components/CodeView/BlobView/ExampleTheme.js
  moon/apps/web/components/CodeView/BlobView/ToolbarPlugin.js
  moon/apps/web/components/CodeView/BlobView/editor.css
  moon/apps/web/components/CodeView/CodeTable.tsx
  moon/apps/web/hooks/useGetBlob.ts
  moon/apps/web/package.json
  moon/apps/web/pages/[org]/code/blob/[...path].tsx
  moon/apps/web/public/icons/LICENSE.md
  moon/apps/web/public/icons/arrow-clockwise.svg
  moon/apps/web/public/icons/arrow-counterclockwise.svg
  moon/apps/web/public/icons/backtop.svg
  moon/apps/web/public/icons/chat-square-quote.svg
  moon/apps/web/public/icons/chevron-down.svg
  moon/apps/web/public/icons/code.svg
  moon/apps/web/public/icons/commit.svg
  moon/apps/web/public/icons/file.svg
  moon/apps/web/public/icons/folder.svg
  moon/apps/web/public/icons/git-pull-request.svg
  moon/apps/web/public/icons/headImage.svg
  moon/apps/web/public/icons/help.svg
  moon/apps/web/public/icons/issues.svg
  moon/apps/web/public/icons/journal-code.svg
  moon/apps/web/public/icons/journal-text.svg
  moon/apps/web/public/icons/justify.svg
  moon/apps/web/public/icons/link.svg
  moon/apps/web/public/icons/list-ol.svg
  moon/apps/web/public/icons/list-ul.svg
  moon/apps/web/public/icons/markdown.svg
  moon/apps/web/public/icons/notification.svg
  moon/apps/web/public/icons/pencil-fill.svg
  moon/apps/web/public/icons/text-center.svg
  moon/apps/web/public/icons/text-left.svg
  moon/apps/web/public/icons/text-paragraph.svg
  moon/apps/web/public/icons/text-right.svg
  moon/apps/web/public/icons/type-bold.svg
  moon/apps/web/public/icons/type-h1.svg
  moon/apps/web/public/icons/type-h2.svg
  moon/apps/web/public/icons/type-h3.svg
  moon/apps/web/public/icons/type-italic.svg
  moon/apps/web/public/icons/type-strikethrough.svg
  moon/apps/web/public/icons/type-underline.svg
  moon/pnpm-lock.yaml
Labels: ui, website

#1079 feat(UI): change style of code-content, and add CommentSection
  moon/apps/web/components/CodeView/BlobView/CodeContent.tsx
  moon/apps/web/components/CodeView/BlobView/CommentEditor.tsx
  moon/apps/web/components/CodeView/BlobView/CommentItem.tsx
  moon/apps/web/components/CodeView/BlobView/CommentSection.tsx
  moon/apps/web/pages/[org]/code/blob/[...path].tsx
Labels: ui, website

#1066 CI: self-hosted macOS support
  .github/install-dep/action.yml
  .github/workflows/base.yml
  monobean/resources/gtk/code_page.ui
  monobean/resources/gtk/hello_page.ui
  monobean/resources/gtk/mega_tab.ui
  monobean/resources/gtk/not_implemented.ui
  monobean/resources/gtk/repo_detail.ui
  monobean/resources/gtk/theme_selector.ui
  monobean/resources/gtk/window.ui
  monobean/resources/icons/symbolic/apps/monobean-archive-restore-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-arrow-down-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-arrow-left-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-arrow-right-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-arrow-up-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-code-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-crop-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-file-text-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-hard-drive-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-info-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-lasso-select-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-list-plus-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-list-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-menu-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-monitor-stop-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-network-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-package-2-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-package-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-refresh-cw-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-save-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-step-back-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-trash-symbolic.svg
  monobean/resources/icons/symbolic/apps/monobean-upload-symbolic.svg
  monobean/resources/org.Web3Infrastructure.Monobean.gresource.xml
Labels: CI
