Repository web3infra-foundation/mega, pull requests merged in 2025-08, with the labels that each got.

#1296 add ALL CVEs' page and cve-info page
  moon/apps/web/pages/[org]/rust/rust-ecosystem/ecosystem-cve/cve-info/[cve-id]/index.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/ecosystem-cve/index.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/index.tsx
  moon/apps/web/public/rust/rust-ecosystem/ecosystem-cve/Frame.png
  moon/apps/web/public/rust/rust-ecosystem/ecosystem-cve/cve-info.png
  moon/apps/web/public/rust/rust-ecosystem/ecosystem-cve/cve-info/cve-info.png
Labels: ui, dashboard

#1300 feat(UI): generate ssh key API's doc
  ceres/src/lfs/lfs_structs.rs
  common/src/config.rs
  jupiter/callisto/src/sea_orm_active_enums.rs
  jupiter/src/lfs_storage/mod.rs
  mono/src/api/conversation/mod.rs
  mono/src/api/mr/mod.rs
  mono/src/api/user/model.rs
  mono/src/api/user/user_router.rs
  mono/src/server/https_server.rs
  moon/packages/types/generated.ts
Labels: ui, mono

#1301 Fix: Add API for Orion in Scorpio and update Orion to fit the changes, allowing it to build successfully.
  jupiter/callisto/src/mod.rs
  jupiter/src/migration/m20250725_103004_add_note.rs
  jupiter/src/storage/note_storage.rs
  libra/src/command/add.rs
  libra/src/command/remove.rs
  libra/tests/command/fetch_test.rs
  libra/tests/command/lfs_test.rs
  libra/tests/command/merge_test.rs
  libra/tests/command/remove_test.rs
  libra/tests/command/revert_test.rs
  mercury/src/internal/index.rs
  mono/src/api/api_router.rs
  mono/src/api/mod.rs
  orion/.env
  orion/Cargo.toml
  orion/src/buck_controller.rs
  scorpio/scorpio.toml
  scorpio/src/daemon/mod.rs
Labels: buck2, building

#1302 feat(UI):Support force-push type, loading position adjustment
  moon/apps/web/components/DiffView/parsedDiffs.ts
  moon/apps/web/components/MrView/MergedItem.tsx
  moon/apps/web/components/MrView/TimelineItems.tsx
  moon/apps/web/components/MrView/item/ForcePushItem.tsx
  moon/apps/web/pages/[org]/mr/[link]/[id].tsx
Labels: ui, dashboard

#1292 为add、diff、remove命令补充测试用例#1257
  .gitignore
  libra/src/command/remove.rs
  libra/tests/command/add_test.rs
  libra/tests/command/diff_test.rs
  libra/tests/command/mod.rs
  libra/tests/command/remove_test.rs
Labels: pre-task, r2cn, libra

#1309 add crate search page and crate info page.update CVE info page styling
  moon/apps/web/pages/[org]/rust/rust-ecosystem/ecosystem-cve/cve-info/[cve-id]/index.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/index.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/search/crate-info/index.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/search/index.tsx
  moon/apps/web/public/rust/rust-ecosystem/ecosystem-cve/cve-info/Frame.png
Labels: ui

#1315 feat(UI): sse docking & add feature of modifing title
  moon/apps/web/components/Issues/IssueDetailPage.tsx
  moon/apps/web/components/MrView/components/Checks/index.tsx
  moon/apps/web/components/MrView/hook/useSSM.ts
  moon/apps/web/hooks/MR/usePostMrTitle.ts
  moon/apps/web/hooks/issues/usePostIssueTitle.ts
  moon/apps/web/next.config.js
  moon/apps/web/package.json
  moon/apps/web/pages/[org]/mr/[link]/index.tsx
  moon/pnpm-lock.yaml
Labels: ui, dashboard

#1313 feat(mono):intorduce bellatrix under orion-server for trigger build
  Cargo.toml
  ceres/Cargo.toml
  ceres/src/api_service/mono_api_service.rs
  ceres/src/model/mr.rs
  ceres/src/pack/import_repo.rs
  ceres/src/pack/mod.rs
  ceres/src/pack/monorepo.rs
  ceres/src/protocol/mod.rs
  ceres/src/protocol/smart.rs
  common/src/config.rs
  config/config-workflow.toml
  config/config.toml
  gateway/src/https_server.rs
  gemini/src/p2p/client.rs
  jupiter/callisto/src/entity_ext/mega_mr.rs
  jupiter/src/storage/issue_storage.rs
  jupiter/src/storage/mono_storage.rs
  jupiter/src/storage/mr_storage.rs
  libra/src/command/diff.rs
  mercury/src/internal/object/tree.rs
  mono/src/api/api_router.rs
  mono/src/api/conversation/conv_router.rs
  mono/src/api/issue/issue_router.rs
  mono/src/api/label/label_router.rs
  mono/src/api/mod.rs
  mono/src/api/mr/mr_router.rs
  mono/src/api/notes/note_router.rs
  mono/src/api/user/user_router.rs
  mono/src/cli.rs
  mono/src/commands/service/http.rs
  mono/src/commands/service/multi.rs
  mono/src/git_protocol/http.rs
  mono/src/git_protocol/ssh.rs
  mono/src/server/http_server.rs
  mono/src/server/mod.rs
  monobean/src/core/mega_core.rs
  moon/packages/types/generated.ts
  neptune/src/lib.rs
  neptune/src/neptune_engine.rs
  orion-server/bellatrix/Cargo.toml
  orion-server/bellatrix/src/lib.rs
  orion-server/bellatrix/src/orion_client/mod.rs
Labels: buck2, building, mono

#1329 feat(UI):Comments support quote and copy
  moon/apps/web/components/Issues/IssueDetailPage.tsx
  moon/apps/web/components/MrView/CommentDropdownMenu.tsx
  moon/apps/web/components/MrView/MRComment.tsx
  moon/apps/web/components/MrView/TimelineItems.tsx
  moon/apps/web/components/SimpleNoteEditor/SimpleNoteContent.tsx
  moon/apps/web/pages/[org]/mr/[link]/index.tsx
Labels: ui, dashboard

#1335 [mono]UPDATE: Alter to CommonPage and Restored content_diff for debug…
  ceres/src/api_service/mono_api_service.rs
  ceres/src/model/mr.rs
  common/src/model.rs
  libra/src/command/diff.rs
  mono/Cargo.toml
  mono/src/api/mr/mod.rs
  mono/src/api/mr/mr_router.rs
  neptune/Cargo.toml
  neptune/src/lib.rs
  neptune/src/model/diff_model.rs
  neptune/src/model/mod.rs
  neptune/src/neptune_engine.rs
Labels: ui, mono

#1381 Gpg API
  .github/install-dep/action.yml
  Cargo.toml
  ceres/Cargo.toml
  ceres/src/api_service/mono_api_service.rs
  common/Cargo.toml
  common/src/errors.rs
  config/config.toml
  jupiter/Cargo.toml
  jupiter/README.md
  jupiter/callisto/src/gpg_key.rs
  jupiter/callisto/src/mod.rs
  jupiter/src/migration/m20250820_102133_gpgkey.rs
  jupiter/src/migration/mod.rs
  jupiter/src/storage/gpg_storage.rs
  jupiter/src/storage/mod.rs
  jupiter/src/tests.rs
  libra/src/cli.rs
  libra/src/command/cherry_pick.rs
  libra/src/command/clone.rs
  libra/src/command/commit.rs
  libra/src/command/fetch.rs
  libra/src/command/merge.rs
  libra/src/command/mod.rs
  libra/src/command/rebase.rs
  libra/src/command/reflog.rs
  libra/src/command/reset.rs
  libra/src/command/stash.rs
  libra/src/command/switch.rs
  libra/src/internal/branch.rs
  libra/src/internal/config.rs
  libra/src/internal/head.rs
  libra/src/internal/model/reflog.rs
  libra/src/internal/reflog.rs
  libra/src/utils/util.rs
  mono/src/api/api_router.rs
  mono/src/api/gpg/gpg_router.rs
  mono/src/api/gpg/mod.rs
  mono/src/api/gpg/model.rs
  mono/src/api/mod.rs
  mono/src/api/mr/mod.rs
  mono/src/api/mr/model.rs
  mono/src/api/mr/mr_router.rs
  mono/src/server/http_server.rs
Labels: ui, mono

#1387 [jupiter]UPDATE:sync entity structure with migrations
  config/config.toml
  jupiter/callisto/src/gpg_key.rs
  jupiter/callisto/src/mod.rs
  jupiter/callisto/src/prelude.rs
  jupiter/callisto/src/user.rs
  jupiter/src/migration/m20250820_102133_gpgkey.rs
Labels: ui, mono

#1390 fix(mono jupiter):Fix the issue of database port detection when mono start(#1386)
  config/config.toml
  jupiter/src/storage/init.rs
Labels: mono

#1392 [mono]FIX: upload full mui-tree
  ceres/src/api_service/mono_api_service.rs
  jupiter/callisto/src/mod.rs
  jupiter/src/storage/gpg_storage.rs
  mono/src/api/gpg/gpg_router.rs
  mono/src/api/mr/mr_router.rs
Labels: ui, mono
