Repository web3infra-foundation/mega, pull requests merged in 2025-09, with the labels that each got.

#1397 feat(UI): add gpg-key setting
  moon/apps/web/components/Setting/GPGKeys.tsx
  moon/apps/web/hooks/useDeleteGPGKeyById.ts
  moon/apps/web/hooks/useGetGPGList.ts
  moon/apps/web/hooks/usePostGPGKey.ts
  moon/apps/web/pages/me/settings/index.tsx
Labels: ui, dashboard

#1400 fix(UI): fix TreeView layout
  moon/apps/web/components/CodeView/BlobView/CodeContent.tsx
  moon/apps/web/components/CodeView/TreeView/CloneTabs.tsx
  moon/apps/web/components/CodeView/TreeView/RepoTree.tsx
  moon/apps/web/pages/[org]/code/blob/[...path].tsx
  moon/apps/web/pages/[org]/code/tree/[...path]/index.tsx
Labels: ui, dashboard

#1399 Restored the document file and modified the scrolling implementation …
  moon/apps/web/pages/[org]/rust/rust-ecosystem/crate-info/[crateName]/index.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/crate-info/[crateName]/layout.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/index.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/search/index.tsx
  moon/apps/web/pages/[org]/rust/rust-news/index.tsx
  moon/apps/web/pages/_document.tsx
Labels: ui, dashboard

#1404 feat(mono): adjust some functions in mono trait
  ceres/src/api_service/import_api_service.rs
  ceres/src/api_service/mod.rs
  ceres/src/api_service/mono_api_service.rs
  ceres/src/pack/import_repo.rs
  ceres/src/pack/mod.rs
  ceres/src/pack/monorepo.rs
  ceres/src/protocol/smart.rs
  jupiter/src/storage/mr_storage.rs
Labels: ui, mono

#1413 [mr_checker] FEAT: MR gpg signature verification
  ceres/src/api_service/mono_api_service.rs
  ceres/src/merge_checker/gpg_signature_checker.rs
  ceres/src/merge_checker/mod.rs
  jupiter/src/storage/gpg_storage.rs
  mono/src/api/gpg/gpg_router.rs
  mono/src/api/gpg/model.rs
  mono/src/api/mr/model.rs
  mono/src/api/mr/mr_router.rs
Labels: ui, mono

#1415 fix(UI): fix type error in DiffView
  moon/apps/web/components/DiffView/FileDiff.tsx
  moon/apps/web/components/DiffView/parsedDiffs.ts
  moon/apps/web/components/Setting/GPGKeys.tsx
  moon/apps/web/hooks/useMrFilesChanged.ts
Labels: ui

#1416 fix(mono): update merge-box API
  ceres/src/merge_checker/gpg_signature_checker.rs
  ceres/src/merge_checker/mod.rs
  ceres/src/merge_checker/mr_sync_checker.rs
  mono/src/api/mr/mod.rs
Labels: ui

#1427 Code Reviewer and Review Checker
  ceres/src/merge_checker/code_review_checker.rs
  ceres/src/merge_checker/gpg_signature_checker.rs
  ceres/src/merge_checker/mod.rs
  jupiter/callisto/src/mega_mr_reviewer.rs
  jupiter/callisto/src/mod.rs
  jupiter/callisto/src/prelude.rs
  jupiter/src/migration/m20250905_163011_add_mr_reviewer.rs
  jupiter/src/migration/mod.rs
  jupiter/src/storage/mod.rs
  jupiter/src/storage/mr_reviewer_storage.rs
  jupiter/src/tests.rs
  mono/src/api/mr/model.rs
  mono/src/api/mr/mr_router.rs
Labels: ui, mono

#1430 fix(mercury): parse commit from bytes lost gpgsig
  mercury/src/internal/object/commit.rs
Labels: bug

#1452 feat:update logic of sse
  moon/apps/web/components/DiffView/FileDiff.tsx
  moon/apps/web/components/MrView/components/Checks/cpns/Task.tsx
  moon/apps/web/components/MrView/components/Checks/cpns/store.ts
  moon/apps/web/components/MrView/components/Checks/index.tsx
  moon/apps/web/hooks/SSE/ssmRequest.ts
  moon/apps/web/hooks/SSE/useGetBuildList.ts
  moon/apps/web/hooks/SSE/useGetHTTPLog.ts
  moon/apps/web/hooks/SSE/useGetMrTask.ts
  moon/apps/web/pages/[org]/mr/[link]/index.tsx
Labels: ui, dashboard

#1456 feat(UI): update MergeBox
  moon/apps/web/components/MrBox/ChecksSection.tsx
  moon/apps/web/components/MrBox/MergeBox.tsx
  moon/apps/web/components/MrBox/hooks/useGetMergeBox.ts
  moon/apps/web/components/MrBox/types/mergeCheck.config.ts
  moon/apps/web/package.json
  moon/pnpm-lock.yaml
Labels: ui, dashboard

#1476 Revert "Decoupling mercury with mega workspace (#1473)"
  ceres/src/api_service/import_api_service.rs
  ceres/src/api_service/mono_api_service.rs
  ceres/src/pack/import_repo.rs
  ceres/src/pack/mod.rs
  ceres/src/pack/monorepo.rs
  common/Cargo.toml
  common/src/errors.rs
  extensions/rag/index/src/qdrant.rs
  jupiter/Cargo.toml
  jupiter/callisto/Cargo.toml
  jupiter/callisto/src/mercury_adapters.rs
  jupiter/callisto/src/mod.rs
  jupiter/src/adapter.rs
  jupiter/src/lib.rs
  jupiter/src/storage/git_db_storage.rs
  jupiter/src/storage/mono_storage.rs
  jupiter/src/utils/converter.rs
  libra/src/command/init.rs
  libra/tests/command/init_test.rs
  mercury/Cargo.toml
  mercury/src/errors.rs
  mercury/src/internal/index.rs
  mercury/src/internal/model/blob.rs
  mercury/src/internal/model/commit.rs
  mercury/src/internal/model/mod.rs
  mercury/src/internal/model/sea_models/commit.rs
  mercury/src/internal/model/sea_models/git_blob.rs
  mercury/src/internal/model/sea_models/git_commit.rs
  mercury/src/internal/model/sea_models/git_tag.rs
  mercury/src/internal/model/sea_models/git_tree.rs
  mercury/src/internal/model/sea_models/mega_blob.rs
  mercury/src/internal/model/sea_models/mega_commit.rs
  mercury/src/internal/model/sea_models/mega_tag.rs
  mercury/src/internal/model/sea_models/mega_tree.rs
  mercury/src/internal/model/sea_models/mod.rs
  mercury/src/internal/model/sea_models/raw_blob.rs
  mercury/src/internal/model/tag.rs
  mercury/src/internal/model/tree.rs
  mercury/src/internal/object/commit.rs
  mercury/src/internal/object/mod.rs
  mercury/src/internal/pack/cache_object.rs
Labels: mono

#1478 feat(cratespro): dependencies,dependents,graph,versions and compare page get data from…
  moon/apps/web/components/Rust/Graph/DependencyGraph.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/crate-info/compare/index.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/crate-info/dependencies/graph/index.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/crate-info/dependencies/index.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/crate-info/dependents/index.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/crate-info/index.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/crate-info/layout.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/crate-info/versions/index.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/search/index.tsx
Labels: ui

#1481 feat: Implement code blame functionality
  ceres/src/api_service/import_api_service.rs
  ceres/src/api_service/mod.rs
  ceres/src/api_service/mono_api_service.rs
  ceres/src/model/blame.rs
  ceres/src/model/mod.rs
  common/src/config.rs
  config/config.toml
  jupiter/Cargo.toml
  jupiter/src/model/blame_dto.rs
  jupiter/src/model/mod.rs
  jupiter/src/service/blame_service.rs
  jupiter/src/service/mod.rs
  jupiter/src/tests.rs
  mega/config.toml
  mono/src/api/api_router.rs
  monobean/src/core/mega_core.rs
  neptune/Cargo.toml
  neptune/src/blame_diff.rs
  neptune/src/lib.rs
Labels: ui, mono

#1484 Feat: Implement the backend part of issue #1449
  ceres/src/api_service/import_api_service.rs
  ceres/src/api_service/mod.rs
  ceres/src/api_service/mono_api_service.rs
  ceres/src/merge_checker/gpg_signature_checker.rs
  ceres/src/model/blame.rs
  common/src/model.rs
  extensions/rag/index/src/qdrant.rs
  jupiter/src/model/blame_dto.rs
  jupiter/src/service/blame_service.rs
  jupiter/src/storage/git_db_storage.rs
  jupiter/src/storage/mono_storage.rs
  jupiter/src/tests.rs
  libra/src/command/init.rs
  libra/tests/command/init_test.rs
  mercury/src/internal/index.rs
  mono/Cargo.toml
  mono/src/api/api_router.rs
  mono/src/api/error.rs
  mono/src/api/mod.rs
  mono/src/api/tag/mod.rs
  mono/src/api/tag/model.rs
  mono/src/api/tag/tag_router.rs
  neptune/src/blame_diff.rs
Labels: ui, mono
