Repository web3infra-foundation/mega, pull requests merged in 2025-07, with the labels that each got.

#1176 refactor(UI):The timeline and tab components of the MR Page
  moon/apps/web/components/DiffView/FileDiff.tsx
  moon/apps/web/components/MrView/MRComment.tsx
  moon/apps/web/components/MrView/TimelineItems.tsx
  moon/apps/web/package.json
  moon/apps/web/pages/[org]/mr/[id].tsx
  moon/pnpm-lock.yaml
  moon/pnpm-workspace.yaml
Labels: ui, dashboard

#1174 Create a new Rag framework based on Mega Warehouse
  Cargo.toml
  extensions/README.md
  extensions/observatory/Cargo.toml
  extensions/observatory/README.md
  extensions/observatory/docker-compose.yml
  extensions/observatory/src/facilities.rs
  extensions/observatory/src/lib.rs
  extensions/observatory/src/model/crate_repo.rs
  extensions/observatory/src/model/crates.rs
  extensions/observatory/src/model/github_repo.rs
  extensions/observatory/src/model/mod.rs
  extensions/rag/.env
  extensions/rag/README.md
  extensions/rag/chat/.gitignore
  extensions/rag/chat/Cargo.toml
  extensions/rag/chat/Dockerfile
  extensions/rag/chat/src/chat.sh
  extensions/rag/chat/src/command.rs
  extensions/rag/chat/src/generation.rs
  extensions/rag/chat/src/lib.rs
  extensions/rag/chat/src/main.rs
  extensions/rag/chat/src/search.rs
  extensions/rag/chat/src/utils.rs
  extensions/rag/chat/src/vectorization.rs
  extensions/rag/index/.gitignore
  extensions/rag/index/Cargo.toml
  extensions/rag/index/Dockerfile
  extensions/rag/index/index.sh
  extensions/rag/index/requirements.txt
  extensions/rag/index/src/command.rs
  extensions/rag/index/src/indexer.rs
  extensions/rag/index/src/lib.rs
  extensions/rag/index/src/main.rs
  extensions/rag/index/src/qdrant.rs
  extensions/rag/index/src/utils.rs
  extensions/rag/index/src/vectorization.rs
  extensions/sync.py
Labels: ai, rag

#1185 [orion](feature): Add MR field support for build model.
  orion-server/Cargo.toml
  orion-server/README.md
  orion-server/src/api.rs
  orion-server/src/model/builds.rs
  orion-server/src/server.rs
  orion/README.md
Labels: buck2

#1191 fix(UI):quick fix Web UI err
  .github/workflows/mono-engine-deploy.yml
  moon/apps/web/components/Issues/IssuePage.tsx
  moon/apps/web/components/Issues/IssuesContent.tsx
  moon/apps/web/components/MrView/index.tsx
  moon/apps/web/hooks/issues/useGetIssueLists.ts
  moon/apps/web/hooks/usePostMrList.ts
Labels: ui, dashboard

#1193 feat(UI):api dockiing & replace the icons
  moon/apps/web/components/Issues/IssueList.tsx
  moon/apps/web/components/Issues/IssueNewPage.tsx
  moon/apps/web/components/Issues/IssuesContent.tsx
  moon/apps/web/components/Issues/Pagenation.tsx
  moon/apps/web/components/Issues/utils/consts.ts
  moon/apps/web/components/Issues/utils/store.tsx
  moon/apps/web/components/MrView/index.tsx
  moon/apps/web/hooks/issues/useGetIssueLists.ts
  moon/apps/web/hooks/usePostMrList.ts
Labels: ui, dashboard

#1198 fix(UI): fix the abnormal UI of new issue page
  moon/apps/web/components/Issues/IssueNewPage.tsx
  moon/apps/web/components/SimpleNoteEditor/SimpleNoteContent.tsx
  moon/apps/web/pages/[org]/issue/new/index.tsx
  moon/apps/web/styles/global.css
Labels: ui, dashboard

#1204 feat: Refactor the tree component, add a file type icon library, and …
  moon/apps/web/components/CodeView/CodeTable.tsx
  moon/apps/web/components/CodeView/FileIcon/FileIcon.tsx
  moon/apps/web/components/CodeView/Table/index.tsx
  moon/apps/web/components/CodeView/TreeView/CloneTabs.tsx
  moon/apps/web/components/CodeView/TreeView/RepoTree.tsx
  moon/apps/web/package.json
  moon/apps/web/pages/[org]/code/blob/[...path].tsx
  moon/apps/web/pages/[org]/code/tree/[...path]/index.tsx
  moon/pnpm-lock.yaml
  moon/pnpm-workspace.yaml
Labels: ui, dashboard

#1221 feat(UI): issue related
  moon/apps/web/components/Issues/IssueDetailPage.tsx
  moon/apps/web/components/Issues/IssueList.tsx
  moon/apps/web/components/Issues/IssueNewPage.tsx
  moon/apps/web/components/Issues/IssuesContent.tsx
  moon/apps/web/components/Issues/utils/consts.ts
  moon/apps/web/components/MrView/index.tsx
  moon/apps/web/components/SimpleNoteEditor/SimpleNoteContent.tsx
  moon/apps/web/pages/[org]/issue/[id]/index.tsx
  moon/apps/web/pages/[org]/issue/new/index.tsx
Labels: ui, dashboard

#1237 add rust news page
  moon/apps/web/components/Sidebar/SidebarCratespro.tsx
  moon/apps/web/pages/[org]/cratespro/index.tsx
  moon/apps/web/pages/[org]/rust/index.tsx
  moon/apps/web/pages/[org]/rust/rust-news/index.tsx
  moon/apps/web/public/rust/Crate Ecosystem.png
  moon/apps/web/public/rust/Rust-Distribth.png
  moon/apps/web/public/rust/Rust-News.png
  moon/apps/web/public/rust/Rust-Tour-Doc.png
  moon/apps/web/public/rust/logo.png
  moon/apps/web/public/rust/normal.png
  moon/apps/web/public/rust/rust-news/up-icon.png
  moon/apps/web/public/rust/search-icon.png
  moon/apps/web/styles/global.css
Labels: ui, dashboard

#1238 feat(UI): added issue suggestions on comment
  .dockerignore
  aria/contents/docs/getting-started/installation/index.mdx
  common/Cargo.toml
  common/src/utils.rs
  docker/README.md
  jupiter/callisto/src/entity_ext/label.rs
  jupiter/callisto/src/entity_ext/mega_issue.rs
  jupiter/callisto/src/entity_ext/mega_mr.rs
  jupiter/callisto/src/entity_ext/mod.rs
  jupiter/src/service/issue_service.rs
  jupiter/src/service/mr_service.rs
  jupiter/src/storage/issue_storage.rs
  jupiter/src/storage/mod.rs
  jupiter/src/storage/mr_storage.rs
  mono/src/api/issue/issue_router.rs
  mono/src/api/issue/mod.rs
  mono/src/api/mr/mr_router.rs
  moon/packages/types/generated.ts
Labels: ui, mono

#1240 feat(UI):Rich text editor supports associated issues
  moon/apps/web/components/MarkdownEditor/MentionList.tsx
  moon/apps/web/components/MrView/MRComment.tsx
  moon/apps/web/components/RichTextRenderer/handlers/LinkIssue.tsx
  moon/apps/web/components/RichTextRenderer/index.tsx
  moon/apps/web/components/SimpleNoteEditor/SimpleNoteContent.tsx
  moon/apps/web/pages/[org]/mr/[id].tsx
  moon/apps/web/styles/prose.css
  moon/packages/editor/src/extensions/LinkIssue.ts
  moon/packages/editor/src/extensions/index.ts
  moon/packages/editor/src/note.ts
Labels: ui, dashboard

#1249 feat: add label page
  moon/apps/web/components/Issues/IssueSearch.tsx
  moon/apps/web/components/Issues/utils/store.tsx
  moon/apps/web/hooks/usePostLabelList.ts
  moon/apps/web/package.json
  moon/apps/web/pages/[org]/labels/index.tsx
  moon/pnpm-lock.yaml
  moon/pnpm-workspace.yaml
Labels: ui, dashboard

#1251 crate ecosystem homepage
  moon/apps/web/pages/[org]/rust/index.tsx
  moon/apps/web/pages/[org]/rust/rust-ecosystem/index.tsx
  moon/apps/web/pages/[org]/rust/rust-news/index.tsx
  moon/apps/web/pages/_document.tsx
  moon/apps/web/public/rust/rust-ecosystem/Frame 166.png
  moon/apps/web/public/rust/rust-ecosystem/Objects - magnifying-glass.png
  moon/apps/web/public/rust/rust-ecosystem/code.png
  moon/apps/web/public/rust/rust-ecosystem/crate.png
  moon/apps/web/public/rust/rust-ecosystem/cve.png
  moon/apps/web/public/rust/rust-ecosystem/down.png
  moon/apps/web/public/rust/rust-ecosystem/homepage.png
  moon/apps/web/public/rust/rust-ecosystem/rust.png
  moon/apps/web/public/rust/rust-ecosystem/search-bg.png
  moon/apps/web/public/rust/rust-ecosystem/上箭头-常态.png
  moon/apps/web/public/rust/rust-ecosystem/下箭头-hover(1).png
  moon/apps/web/public/rust/rust-ecosystem/下箭头-hover.png
  moon/apps/web/styles/global.css
Labels: ui, dashboard

#1260 fix: repair the assignees staty status
  moon/apps/web/components/Issues/IssueDetailPage.tsx
  moon/apps/web/components/Issues/IssueNewPage.tsx
  moon/apps/web/components/Issues/IssuesContent.tsx
  moon/apps/web/components/Issues/utils/sideEffect.tsx
  moon/apps/web/components/MemberAvatar/index.tsx
  moon/apps/web/components/MrView/TimelineItems.tsx
  moon/apps/web/components/MrView/index.tsx
  moon/apps/web/hooks/issues/useGetIssueDetail.ts
  moon/apps/web/hooks/issues/usePostIssueAssignees.ts
  moon/apps/web/hooks/issues/usePostMRAssignees.ts
  moon/apps/web/pages/[org]/issue/[link]/[id]/index.tsx
  moon/apps/web/pages/[org]/mr/[id].tsx
  moon/apps/web/pages/[org]/mr/[link]/[id].tsx
Labels: ui, dashboard

#1278 feat(UI): update API domain to https
  moon/apps/sync-server/src/api.ts
  moon/apps/web/next.config.js
  moon/packages/config/src/index.ts
Labels: ui, dashboard
