Repository web3infra-foundation/mega, pull requests merged in 2025-06, with the labels that each got.

#1083 feat(UI): add Radix UI table component
  moon/apps/web/components/CodeView/CodeTable.tsx
  moon/apps/web/components/CodeView/Table/index.tsx
  moon/apps/web/components/CodeView/Table/type.d.ts
  moon/apps/web/components/CodeView/index.tsx
  moon/apps/web/package.json
  moon/apps/web/pages/[org]/code/index.tsx
  moon/apps/web/pages/[org]/code/tree/[...path]/index.tsx
  moon/apps/web/pages/_app.tsx
  moon/pnpm-lock.yaml
Labels: ui, dashboard

#1095 feat(UI): add loading logic
  moon/apps/web/components/CodeView/CodeTable.tsx
  moon/apps/web/components/CodeView/Table/index.tsx
  moon/apps/web/components/CodeView/TableWithLoading/index.tsx
  moon/apps/web/components/CodeView/index.tsx
  moon/apps/web/pages/[org]/code/tree/[...path]/index.tsx
Labels: ui, website

#1098 feat(UI): replace antd Icons to campsits'&add Icons story
  moon/apps/web/.storybook/preview.tsx
  moon/apps/web/components/CodeView/TreeView/CloneTabs.tsx
  moon/apps/web/components/CodeView/TreeView/RepoTree.tsx
  moon/apps/web/components/Issues/IssueDetailPage.tsx
  moon/packages/ui/src/Icons/Icons.stories.tsx
Labels: ui, website

#1103 feat(UI): issue main page rebuild&add pagination component
  moon/apps/web/components/CodeView/Table/index.tsx
  moon/apps/web/components/IndexPages/components.tsx
  moon/apps/web/components/Issues/IssueIndex.tsx
  moon/apps/web/components/Issues/IssueList.tsx
  moon/apps/web/components/Issues/IssueNewPage.tsx
  moon/apps/web/components/Issues/IssuePage.tsx
  moon/apps/web/components/Issues/IssuesContent.tsx
  moon/apps/web/components/Issues/Pagenation.tsx
  moon/apps/web/components/Issues/utils/getPages.ts
  moon/apps/web/components/Issues/utils/store.tsx
  moon/apps/web/components/Titlebar/BreadcrumbPageIcons.tsx
  moon/apps/web/pages/[org]/issue/index.tsx
Labels: ui, website

#1107 fix:[mono] optimize commit_info related apis
  ceres/src/api_service/import_api_service.rs
  ceres/src/api_service/mod.rs
  ceres/src/api_service/mono_api_service.rs
  ceres/src/model/git.rs
  config/config.toml
  jupiter/src/storage/mod.rs
  mono/src/api/api_router.rs
  mono/src/server/https_server.rs
  moon/packages/types/generated.ts
Labels: ui, mono

#1089 Update mono service in services.yml
  .github/workflows/base.yml
  .github/workflows/services.yml
  config/config-workflow.toml
  libra/tests/command/clone_test.rs
  mega/Cargo.toml
  mega/tests/service_test.rs
Labels: CI

#1109 refactor(UI):Display the data returned by the file-changed page in ch…
  moon/apps/web/components/DiffView/FileDiff.tsx
  moon/apps/web/components/DiffView/parsedDiffs.ts
  moon/apps/web/package.json
  moon/apps/web/pages/[org]/mr/[id].tsx
  moon/apps/web/pages/_app.tsx
  moon/pnpm-lock.yaml
Labels: ui

#1113 fix(UI):The page crashes when the diff data is incomplete
  moon/apps/web/components/DiffView/FileDiff.tsx
Labels: ui

#1124 fix(UI):Fix issue page not navigating to other pages
  moon/apps/web/components/Issues/IssueList.tsx
Labels: ui, dashboard

#1135 feat(UI) completion of issue page&fix the bug of navigation
  moon/apps/web/components/Issues/IssueDetailPage.tsx
  moon/apps/web/components/Issues/IssueIndex.tsx
  moon/apps/web/components/Issues/IssueList.tsx
  moon/apps/web/components/Issues/IssuesContent.tsx
  moon/apps/web/components/Issues/Pagenation.tsx
  moon/apps/web/components/Issues/utils/consts.ts
  moon/apps/web/components/Issues/utils/generateAllMenuItems.ts
  moon/apps/web/components/Issues/utils/store.tsx
  moon/apps/web/pages/[org]/issue/[id]/index.tsx
  moon/apps/web/pages/[org]/issue/new/index.tsx
  moon/apps/web/pages/_app.tsx
  moon/packages/ui/src/Menu/types.ts
Labels: ui, dashboard

#1136 feat(UI):File-change supports files such as dockerfile, gitignore and…
  moon/apps/web/components/DiffView/FileDiff.tsx
  moon/apps/web/components/DiffView/parsedDiffs.ts
Labels: ui, dashboard

#1139 refactor(UI): The rich text editing box uses the tiptap component
  moon/apps/web/components/MrView/MRComment.tsx
  moon/apps/web/components/SimpleNoteEditor/SimpleNoteContent.tsx
  moon/apps/web/components/SimpleNoteEditor/useSimpleNoteEditor.tsx
  moon/apps/web/pages/[org]/mr/[id].tsx
Labels: ui, dashboard

#1141 feat(UI):The editor has added the button function
  moon/apps/web/components/Reactions/ComposerReactionPicker.tsx
  moon/apps/web/components/SimpleNoteEditor/SimpleNoteContent.tsx
  moon/apps/web/pages/[org]/mr/[id].tsx
Labels: ui, dashboard

#1145 feat(UI): add support for issue mentions in MentionList component
  moon/apps/web/components/MarkdownEditor/MentionList.tsx
Labels: ui, dashboard

#1149 Add model in the default folder and refactoring README.md of mercury
  config/config.toml
  mercury/BUCK
  mercury/README.md
  mercury/delta/BUCK
  mercury/delta/README.md
  mercury/delta/src/lib.rs
  mercury/zstdelta/README.md
Labels: documentation

#1151 feat(UI): expand the click range of CodeContent
  moon/apps/web/components/CodeView/BlobView/CodeContent.tsx
Labels: ui, dashboard

#1154 feat: add mr/issue label join query, upadte files-changed api
  jupiter/callisto/src/item_labels.rs
  jupiter/callisto/src/label.rs
  jupiter/callisto/src/mega_issue.rs
  jupiter/callisto/src/mega_mr.rs
  jupiter/src/storage/issue_storage.rs
  jupiter/src/storage/mr_storage.rs
  mono/Cargo.toml
  mono/src/api/issue/mod.rs
  mono/src/api/mr/mod.rs
  mono/src/api/mr/mr_router.rs
  moon/packages/types/generated.ts
Labels: rust, ui

#1163 fix: Echo message information for the table component and roll back t…
  moon/apps/web/components/CodeView/CodeTable.tsx
  moon/apps/web/components/CodeView/Table/type.d.ts
  moon/apps/web/components/DiffView/FileDiff.tsx
  moon/apps/web/components/DiffView/TreeView.tsx
Labels: ui, dashboard

#1168 fix something
  moon/apps/web/components/CodeView/BlobView/CodeContent.tsx
  moon/apps/web/components/MarkdownEditor/MentionList.tsx
Labels: ui, dashboard

#1172 feat(UI): rebuild new issue page & fix some problems
  moon/apps/web/components/Issues/IssueNewPage.tsx
  moon/apps/web/components/Issues/IssuesContent.tsx
  moon/apps/web/components/Issues/utils/extractText.ts
  moon/apps/web/components/Issues/utils/mergeDuplicate.ts
  moon/apps/web/components/Issues/utils/pickWithReflectDeep.ts
  moon/apps/web/components/MrView/index.tsx
  moon/apps/web/next.config.js
  moon/apps/web/package.json
  moon/apps/web/pages/[org]/issue/new/index.tsx
  moon/pnpm-lock.yaml
Labels: ui, dashboard
